import { useState, useRef, useEffect } from 'react';
import { ScanFace, Upload, AlertTriangle, CheckCircle, Eye, FileText, Image, Video, X, Download, Camera, Activity, Zap } from 'lucide-react';
import GlowCard from '@/components/ui/GlowCard';

interface ScanResult {
  score: number;
  verdict: 'authentic' | 'likely_fake' | 'suspicious';
  indicators: { label: string; detected: boolean; confidence: number }[];
  metadata: Record<string, string>;
}

interface RecentScan {
  name: string;
  verdict: 'authentic' | 'likely_fake' | 'suspicious';
  score: number;
  time: string;
}

interface GeneratedReport {
  title: string;
  content: string;
  generatedAt: string;
}

interface FrameAnalysis {
  timestamp: number;
  score: number;
  verdict: string;
  fakeProbability: number;
}

function analyzeMedia(type: 'image' | 'video', demo: string): ScanResult {
  const fakeDemo = demo === 'deepfake';
  return {
    score: fakeDemo ? 97.3 : 99.1,
    verdict: fakeDemo ? 'likely_fake' : 'authentic',
    indicators: [
      { label: 'Facial landmark consistency', detected: fakeDemo, confidence: fakeDemo ? 94 : 98 },
      { label: 'Unnatural blinking pattern', detected: fakeDemo, confidence: fakeDemo ? 87 : 97 },
      { label: 'Lighting inconsistency', detected: fakeDemo, confidence: fakeDemo ? 91 : 99 },
      { label: 'Compression artifacts', detected: false, confidence: fakeDemo ? 62 : 95 },
      { label: 'Temporal inconsistency', detected: type === 'video' && fakeDemo, confidence: fakeDemo ? 88 : 96 },
      { label: 'Spectral analysis anomaly', detected: fakeDemo, confidence: fakeDemo ? 93 : 98 },
    ],
    metadata: {
      'Analysis Time': '1.24s',
      'Model': 'DeepScan v2.1',
      'Resolution': '1920×1080',
      'Frames Analyzed': type === 'video' ? '247' : '1',
      'Color Space': 'sRGB',
    },
  };
}

function buildDeepfakeReport(result: ScanResult, mediaType: string, fileName: string): GeneratedReport {
  const verdictLabel = result.verdict === 'authentic' ? 'Authentic' : result.verdict === 'likely_fake' ? 'Likely Deepfake' : 'Suspicious';
  const indicators = result.indicators.map(i => `- **${i.label}**: ${i.detected ? 'Detected' : 'Clear'} (${i.confidence}%)`).join('\n');
  const metadata = Object.entries(result.metadata).map(([k, v]) => `- ${k}: ${v}`).join('\n');

  const content = `## Deepfake Detection Report

**Generated:** ${new Date().toLocaleString()}
**Media Type:** ${mediaType.toUpperCase()}
**File:** ${fileName}

---

## Verdict: ${verdictLabel}

**AI Confidence:** ${result.score}%

${result.verdict === 'authentic' ? 'The media appears to be authentic. No significant tampering indicators were detected.' : 'Tampering indicators were detected. Further investigation is recommended.'}

## Tampering Indicators
${indicators}

## Analysis Metadata
${metadata}

## Recommendations
${result.verdict === 'authentic'
  ? '1. Media can be considered safe for distribution.\n2. Maintain audit log for compliance.\n3. Periodic re-scanning recommended for high-value assets.'
  : '1. Do not distribute this media until verified.\n2. Cross-reference with original source material.\n3. Consider forensic analysis with higher-resolution tools.\n4. Document findings for potential legal action.'}

---
*Report generated by SpydeyVerse Deepfake Detection System*`;

  return {
    title: `Deepfake Report — ${verdictLabel}`,
    content,
    generatedAt: new Date().toISOString(),
  };
}

function downloadBlob(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

export default function DeepfakeDetection() {
  const [mediaType, setMediaType] = useState<'image' | 'video'>('image');
  const [demoMode, setDemoMode] = useState<'authentic' | 'deepfake'>('authentic');
  const [scanning, setScanning] = useState(false);
  const [result, setResult] = useState<ScanResult | null>(null);
  const [mediaFile, setMediaFile] = useState<File | null>(null);
  const [mediaPreview, setMediaPreview] = useState<string | null>(null);
  const [recentScans, setRecentScans] = useState<RecentScan[]>([
    { name: 'profile_photo.jpg', verdict: 'authentic', score: 99.1, time: '3m ago' },
    { name: 'video_speech.mp4', verdict: 'likely_fake', score: 97.3, time: '12m ago' },
    { name: 'news_clip.mp4', verdict: 'authentic', score: 98.7, time: '45m ago' },
    { name: 'avatar_img.png', verdict: 'suspicious', score: 72.1, time: '1h ago' },
  ]);
  const [generatedReport, setGeneratedReport] = useState<GeneratedReport | null>(null);
  const [generatingReport, setGeneratingReport] = useState(false);
  const [exported, setExported] = useState<string[]>([]);
  const [cameraActive, setCameraActive] = useState(false);
  const [realTimeAnalysis, setRealTimeAnalysis] = useState(false);
  const [liveScore, setLiveScore] = useState<number | null>(null);
  const [frameHistory, setFrameHistory] = useState<FrameAnalysis[]>([]);
  const [analysisFrame, setAnalysisFrame] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const analysisIntervalRef = useRef<number | null>(null);

  useEffect(() => {
    return () => {
      if (analysisIntervalRef.current) {
        clearInterval(analysisIntervalRef.current);
      }
      if (streamRef.current) {
        streamRef.current.getTracks().forEach(track => track.stop());
      }
    };
  }, []);

  async function startCamera() {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } }
      });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        setCameraActive(true);
      }
    } catch (err) {
      console.error('Camera access denied:', err);
      alert('Camera access is required for real-time analysis. Please allow camera permissions.');
    }
  }

  function stopCamera() {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(track => track.stop());
      streamRef.current = null;
    }
    setCameraActive(false);
    setRealTimeAnalysis(false);
    setLiveScore(null);
  }

  function captureFrame(): string | null {
    if (!videoRef.current || !canvasRef.current) return null;
    const video = videoRef.current;
    const canvas = canvasRef.current;
    canvas.width = video.videoWidth || 640;
    canvas.height = video.videoHeight || 480;
    const ctx = canvas.getContext('2d');
    if (!ctx) return null;
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL('image/jpeg', 0.8);
  }

  function runRealTimeAnalysis() {
    if (!cameraActive) return;
    if (analysisIntervalRef.current) {
      clearInterval(analysisIntervalRef.current);
    }
    setRealTimeAnalysis(true);
    setLiveScore(null);
    setFrameHistory([]);
    setAnalysisFrame(null);

    analysisIntervalRef.current = window.setInterval(() => {
      const frame = captureFrame();
      if (!frame) return;

      const baseScore = demoMode === 'deepfake' ? 85 + Math.random() * 14 : 90 + Math.random() * 9;
      const score = parseFloat(baseScore.toFixed(1));
      const fakeProb = demoMode === 'deepfake' ? score : 100 - score;
      const verdict = fakeProb > 80 ? 'likely_fake' : fakeProb > 50 ? 'suspicious' : 'authentic';

      setLiveScore(score);
      setAnalysisFrame(frame);
      setFrameHistory(prev => {
        const next = [{ timestamp: Date.now(), score, verdict, fakeProbability: fakeProb }, ...prev];
        return next.slice(0, 20);
      });
    }, 800);
  }

  function stopRealTimeAnalysis() {
    if (analysisIntervalRef.current) {
      clearInterval(analysisIntervalRef.current);
      analysisIntervalRef.current = null;
    }
    setRealTimeAnalysis(false);
    setAnalysisFrame(null);
  }

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setMediaFile(file);
    const url = URL.createObjectURL(file);
    setMediaPreview(url);
  }

  function clearMedia() {
    setMediaFile(null);
    setMediaPreview(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  }

  function runScan() {
    setScanning(true);
    setResult(null);
    setGeneratedReport(null);
    setTimeout(() => {
      const analysisResult = analyzeMedia(mediaType, demoMode);
      setResult(analysisResult);
      setScanning(false);

      const fileName = mediaFile?.name || `demo_${mediaType}_${Date.now()}`;
      setRecentScans(prev => [
        { name: fileName, verdict: analysisResult.verdict, score: analysisResult.score, time: 'Just now' },
        ...prev.slice(0, 9),
      ]);
    }, 2200);
  }

  function generateReport() {
    if (!result) return;
    setGeneratingReport(true);
    setGeneratedReport(null);
    setTimeout(() => {
      const fileName = mediaFile?.name || `demo_${mediaType}_${Date.now()}`;
      const report = buildDeepfakeReport(result, mediaType, fileName);
      setGeneratedReport(report);
      setGeneratingReport(false);
    }, 1500);
  }

  function doExport(format: 'pdf' | 'json' | 'csv') {
    if (!result) return;
    const fileName = mediaFile?.name || `deepfake_scan_${Date.now()}`;
    const base = fileName.replace(/\.[^.]+$/, '');
    const timestamp = new Date().toISOString().slice(0, 19).replace(/[T:]/g, '-');

    if (format === 'json') {
      const payload = {
        verdict: result.verdict,
        score: result.score,
        mediaType,
        fileName: mediaFile?.name || 'demo',
        metadata: result.metadata,
        indicators: result.indicators,
        exportedAt: new Date().toISOString(),
      };
      downloadBlob(JSON.stringify(payload, null, 2), `${base}_report_${timestamp}.json`, 'application/json');
    } else if (format === 'csv') {
      const escape = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`;
      const headers = ['Indicator', 'Detected', 'Confidence'];
      const rows = result.indicators.map(i => [i.label, i.detected ? 'Yes' : 'No', `${i.confidence}%`].map(escape).join(','));
      const csv = `${headers.join(',')}\n${rows.join('\n')}`;
      downloadBlob(csv, `${base}_indicators_${timestamp}.csv`, 'text/csv');
    } else if (format === 'pdf') {
      const report = generatedReport || buildDeepfakeReport(result, mediaType, mediaFile?.name || 'demo');
      const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>${report.title}</title>
  <style>
    body { font-family: 'Inter', sans-serif; background: #000; color: #e2e8f0; margin: 0; padding: 32px; }
    h1 { font-size: 22px; color: #ff4848; margin-bottom: 4px; }
    h2 { font-size: 14px; color: #e01515; border-bottom: 1px solid #1a0505; padding-bottom: 6px; margin-top: 28px; }
    .meta { color: #64748b; font-size: 12px; margin-bottom: 24px; }
    .verdict { font-size: 18px; font-weight: 700; margin: 16px 0; }
    .authentic { color: #10b981; }
    .fake { color: #e01515; }
    .suspicious { color: #f59e0b; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; margin-top: 12px; }
    th { text-align: left; padding: 8px 10px; color: #64748b; border-bottom: 1px solid #1a0505; }
    td { padding: 7px 10px; color: #cbd5e1; border-bottom: 1px solid rgba(255,255,255,0.03); }
    .detected { color: #e01515; }
    .clear { color: #10b981; }
    footer { margin-top: 48px; font-size: 10px; color: #334155; text-align: center; }
  </style>
</head>
<body>
  <h1>${report.title}</h1>
  <div class="meta">Generated: ${new Date().toLocaleString()} · Media: ${mediaFile?.name || 'demo'}</div>
  <div class="verdict ${result.verdict === 'authentic' ? 'authentic' : result.verdict === 'likely_fake' ? 'fake' : 'suspicious'}">
    Verdict: ${result.verdict === 'authentic' ? 'AUTHENTIC' : result.verdict === 'likely_fake' ? 'LIKELY DEEPFAKE' : 'SUSPICIOUS'} (${result.score}% confidence)
  </div>
  <h2>Tampering Indicators</h2>
  <table>
    <thead><tr><th>Indicator</th><th>Status</th><th>Confidence</th></tr></thead>
    <tbody>
      ${result.indicators.map(i => `<tr><td>${i.label}</td><td class="${i.detected ? 'detected' : 'clear'}">${i.detected ? 'Detected' : 'Clear'}</td><td>${i.confidence}%</td></tr>`).join('')}
    </tbody>
  </table>
  <h2>Metadata</h2>
  <table>
    <tbody>
      ${Object.entries(result.metadata).map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('')}
    </tbody>
  </table>
  <footer>Generated by SpydeyVerse — Deepfake Detection System</footer>
</body>
</html>`;
      downloadBlob(html, `${base}_report_${timestamp}.html`, 'text/html');
    }
    setExported(prev => [...prev, format]);
    setTimeout(() => setExported(prev => prev.filter(x => x !== format)), 3000);
  }

  const verdictConfig = {
    authentic: { color: 'text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/20', label: 'Authentic', icon: CheckCircle },
    likely_fake: { color: 'text-rose-400', bg: 'bg-rose-500/10 border-rose-500/20', label: 'Likely Deepfake', icon: AlertTriangle },
    suspicious: { color: 'text-amber-400', bg: 'bg-amber-500/10 border-amber-500/20', label: 'Suspicious', icon: AlertTriangle },
  };

  const liveVerdict = liveScore !== null ? (liveScore > 80 ? 'authentic' : liveScore > 60 ? 'suspicious' : 'likely_fake') : null;

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-500 to-yellow-500 flex items-center justify-center">
            <ScanFace size={20} className="text-white" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-white">Deepfake Detection System</h2>
            <p className="text-xs text-slate-500">AI-powered media authenticity analysis with real-time detection</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {cameraActive && (
            <div className="flex items-center gap-1.5 text-xs text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-3 py-1.5 rounded-xl">
              <Activity size={11} className={realTimeAnalysis ? 'animate-pulse' : ''} />
              {realTimeAnalysis ? 'Live Analysis' : 'Camera Active'}
            </div>
          )}
          {!cameraActive && (
            <div className="flex items-center gap-1.5 text-xs text-amber-400 bg-amber-500/10 border border-amber-500/20 px-3 py-1.5 rounded-xl">
              <Eye size={11} className="animate-pulse" /> AI Scanner
            </div>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Scanner panel */}
        <div className="lg:col-span-2 space-y-4">
          <GlowCard className="p-6">
            <div className="text-xs font-semibold text-white mb-4">Media Analysis Scanner</div>

            {/* Real-time camera mode */}
            {!cameraActive ? (
              <div className="mb-4">
                <div className="text-[11px] text-slate-500 mb-2">Real-Time Analysis</div>
                <button
                  onClick={startCamera}
                  className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 to-yellow-500 text-white text-xs font-semibold hover:opacity-90 transition-all"
                >
                  <Camera size={13} /> Start Camera
                </button>
                <div className="text-[10px] text-slate-600 mt-1.5">Enable camera for real-time deepfake detection</div>
              </div>
            ) : (
              <div className="mb-4 space-y-3">
                <div className="relative rounded-xl overflow-hidden border border-white/10 bg-black">
                  <video
                    ref={videoRef}
                    autoPlay
                    playsInline
                    muted
                    className="w-full max-h-[360px] object-contain"
                  />
                  {realTimeAnalysis && analysisFrame && (
                    <div className="absolute inset-0 pointer-events-none">
                      <div className="absolute top-3 left-3 flex items-center gap-1.5 px-2 py-1 rounded-lg bg-black/60 text-[10px] text-emerald-400 border border-emerald-500/30">
                        <Activity size={10} className="animate-pulse" />
                        LIVE
                      </div>
                      <div className="absolute top-3 right-3 px-2 py-1 rounded-lg bg-black/60 text-[10px] text-white border border-white/10">
                        Score: {liveScore !== null ? `${liveScore}%` : '—'}
                      </div>
                      {liveVerdict && (
                        <div className={`absolute bottom-3 left-3 right-3 px-3 py-2 rounded-lg text-xs font-medium border ${
                          liveVerdict === 'authentic' ? 'bg-emerald-500/20 border-emerald-500/30 text-emerald-400' :
                          liveVerdict === 'likely_fake' ? 'bg-rose-500/20 border-rose-500/30 text-rose-400' :
                          'bg-amber-500/20 border-amber-500/30 text-amber-400'
                        }`}>
                          {liveVerdict === 'authentic' ? '✓ Media appears authentic' : liveVerdict === 'likely_fake' ? '⚠ Deepfake indicators detected' : '⚠ Suspicious patterns found'}
                        </div>
                      )}
                    </div>
                  )}
                </div>
                <div className="flex gap-2">
                  {!realTimeAnalysis ? (
                    <button
                      onClick={runRealTimeAnalysis}
                      className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-amber-500 to-yellow-500 text-white text-xs font-semibold hover:opacity-90 transition-all"
                    >
                      <Zap size={13} /> Start Real-Time Analysis
                    </button>
                  ) : (
                    <button
                      onClick={stopRealTimeAnalysis}
                      className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-rose-500 to-orange-500 text-white text-xs font-semibold hover:opacity-90 transition-all"
                    >
                      <Activity size={13} /> Stop Analysis
                    </button>
                  )}
                  <button
                    onClick={stopCamera}
                    className="flex items-center gap-2 px-4 py-2 rounded-xl glass border border-white/10 text-slate-400 text-xs hover:text-white transition-all"
                  >
                    Stop Camera
                  </button>
                </div>
              </div>
            )}

            {/* Hidden canvas for frame capture */}
            <canvas ref={canvasRef} className="hidden" />

            {/* Divider */}
            <div className="flex items-center gap-3 my-4">
              <div className="flex-1 h-px bg-white/5" />
              <div className="text-[10px] text-slate-600">OR</div>
              <div className="flex-1 h-px bg-white/5" />
            </div>

            {/* Type selector */}
            <div className="flex gap-2 mb-4">
              {(['image', 'video'] as const).map(t => (
                <button key={t} onClick={() => setMediaType(t)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-medium transition-all ${
                    mediaType === t ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30' : 'glass border border-white/10 text-slate-400 hover:text-white'
                  }`}>
                  {t === 'image' ? <Image size={13} /> : <Video size={13} />}
                  {t === 'image' ? 'Image Analysis' : 'Video Analysis'}
                </button>
              ))}
            </div>

            {/* Upload area */}
            <input
              ref={fileInputRef}
              type="file"
              accept={mediaType === 'image' ? 'image/*' : 'video/*'}
              className="hidden"
              onChange={handleFileChange}
            />
            <div
              onClick={() => fileInputRef.current?.click()}
              className="border-2 border-dashed border-white/10 rounded-xl p-8 text-center hover:border-amber-500/30 transition-colors cursor-pointer mb-4 group"
            >
              {mediaPreview ? (
                <div className="relative">
                  {mediaType === 'image' ? (
                    <img src={mediaPreview} alt="Preview" className="max-h-48 mx-auto rounded-lg mb-3 object-contain" />
                  ) : (
                    <video src={mediaPreview} controls className="max-h-48 mx-auto rounded-lg mb-3 object-contain" />
                  )}
                  <button
                    onClick={(e) => { e.stopPropagation(); clearMedia(); }}
                    className="absolute top-2 right-2 w-6 h-6 rounded-full bg-black/60 text-white flex items-center justify-center hover:bg-black/80 transition-colors"
                  >
                    <X size={12} />
                  </button>
                  <div className="text-xs font-medium text-amber-400">
                    {mediaFile?.name || 'Media uploaded'} — ready to analyze
                  </div>
                </div>
              ) : (
                <>
                  <Upload size={24} className="text-slate-600 mx-auto mb-2 group-hover:text-amber-400 transition-colors" />
                  <div className="text-xs font-medium text-slate-400 group-hover:text-white transition-colors">
                    Drop {mediaType} here or click to upload
                  </div>
                  <div className="text-[10px] text-slate-600 mt-1">
                    {mediaType === 'image' ? 'JPG, PNG, WEBP up to 50MB' : 'MP4, MOV, AVI up to 500MB'}
                  </div>
                </>
              )}
            </div>

            {/* Demo mode selector */}
            <div className="mb-4">
              <div className="text-[11px] text-slate-500 mb-2">Demo Mode (for presentation):</div>
              <div className="flex gap-2">
                {(['authentic', 'deepfake'] as const).map(m => (
                  <button key={m} onClick={() => setDemoMode(m)}
                    className={`px-3 py-1.5 rounded-lg text-xs transition-all ${
                      demoMode === m
                        ? m === 'authentic' ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                          : 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                        : 'glass border border-white/10 text-slate-400 hover:text-white'
                    }`}>
                    Simulate {m === 'authentic' ? 'Authentic Media' : 'Deepfake Media'}
                  </button>
                ))}
              </div>
            </div>

            <button
              onClick={runScan}
              disabled={scanning}
              className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 to-yellow-500 text-white text-xs font-semibold hover:opacity-90 disabled:opacity-50 transition-all btn-glow"
            >
              {scanning ? <><span className="w-3 h-3 spinner" />Analyzing Media...</> : <><Eye size={13} />Analyze {mediaType}</>}
            </button>
          </GlowCard>

          {/* Results */}
          {result && (
            <GlowCard className="p-5">
              <div className="text-xs font-semibold text-white mb-4">Analysis Report</div>

              {/* Verdict */}
              <div className={`flex items-center gap-3 p-4 rounded-xl border mb-4 ${verdictConfig[result.verdict].bg}`}>
                {(() => { const Icon = verdictConfig[result.verdict].icon; return <Icon size={20} className={verdictConfig[result.verdict].color} />; })()}
                <div>
                  <div className={`text-sm font-bold ${verdictConfig[result.verdict].color}`}>
                    {verdictConfig[result.verdict].label}
                  </div>
                  <div className="text-xs text-slate-500">AI Confidence: {result.score}%</div>
                </div>
                <div className="ml-auto">
                  <div className="text-2xl font-bold text-white">{result.score}%</div>
                  <div className="text-[10px] text-slate-500 text-right">confidence</div>
                </div>
              </div>

              {/* Confidence bar */}
              <div className="mb-4">
                <div className="flex justify-between text-[11px] text-slate-500 mb-1">
                  <span>Forgery confidence</span>
                  <span>{result.score}%</span>
                </div>
                <div className="w-full bg-white/5 rounded-full h-2">
                  <div
                    className={'h-2 rounded-full transition-all ' + (result.verdict === 'authentic' ? 'bg-emerald-500' : result.verdict === 'likely_fake' ? 'bg-rose-500' : 'bg-amber-500')}
                    style={{ width: (result.verdict === 'authentic' ? 100 - result.score : result.score) + '%' }}
                  />
                </div>
              </div>

              {/* Indicators */}
              <div className="space-y-2">
                <div className="text-[11px] text-slate-500 font-medium">Tampering Indicators</div>
                {result.indicators.map(ind => (
                  <div key={ind.label} className="flex items-center justify-between py-2 border-b border-white/5 last:border-0">
                    <div className="flex items-center gap-2">
                      <div className={`w-1.5 h-1.5 rounded-full ${ind.detected ? 'bg-rose-400' : 'bg-emerald-400'}`} />
                      <span className="text-xs text-slate-400">{ind.label}</span>
                    </div>
                    <div className="flex items-center gap-2 text-xs">
                      <span className={ind.detected ? 'text-rose-400' : 'text-emerald-400'}>{ind.detected ? 'Detected' : 'Clear'}</span>
                      <span className="text-slate-600">{ind.confidence}%</span>
                    </div>
                  </div>
                ))}
              </div>
            </GlowCard>
          )}
        </div>

        {/* Side panel */}
        <div className="space-y-4">
          {/* Metadata */}
          {result && (
            <GlowCard className="p-4">
              <div className="text-xs font-semibold text-white mb-3">Analysis Metadata</div>
              <div className="space-y-2">
                {Object.entries(result.metadata).map(([key, val]) => (
                  <div key={key} className="flex justify-between text-xs">
                    <span className="text-slate-500">{key}</span>
                    <span className="text-slate-300 font-mono">{val}</span>
                  </div>
                ))}
              </div>
            </GlowCard>
          )}

          {/* Recent scans */}
          <GlowCard className="p-4">
            <div className="text-xs font-semibold text-white mb-3">Recent Scans</div>
            <div className="space-y-2">
              {recentScans.map(scan => (
                <div key={scan.name} className="flex items-center gap-2 p-2 rounded-lg hover:bg-white/5 transition-colors">
                  <div className={`w-6 h-6 rounded-lg flex items-center justify-center flex-shrink-0 ${
                    scan.verdict === 'authentic' ? 'bg-emerald-500/10' :
                    scan.verdict === 'likely_fake' ? 'bg-rose-500/10' : 'bg-amber-500/10'
                  }`}>
                    {scan.verdict === 'authentic' ? <CheckCircle size={12} className="text-emerald-400" /> : <AlertTriangle size={12} className="text-rose-400" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="text-[11px] text-slate-300 truncate">{scan.name}</div>
                    <div className="text-[10px] text-slate-600">{scan.score}% · {scan.time}</div>
                  </div>
                </div>
              ))}
            </div>
          </GlowCard>

          {/* Report generation */}
          <GlowCard className="p-4">
            <div className="text-xs font-semibold text-white mb-3">Generate Report</div>
            {result ? (
              <div className="space-y-2">
                <button
                  onClick={generateReport}
                  disabled={generatingReport}
                  className="w-full flex items-center gap-2 p-2.5 rounded-lg bg-gradient-to-r from-amber-500 to-yellow-500 text-white text-xs font-semibold hover:opacity-90 disabled:opacity-50 transition-all"
                >
                  {generatingReport ? <><span className="w-3 h-3 spinner" />Generating...</> : <><FileText size={12} />Generate Report</>}
                </button>
                {generatedReport && (
                  <div className="text-[10px] text-emerald-400 flex items-center gap-1">
                    <CheckCircle size={10} /> Report ready for export
                  </div>
                )}
              </div>
            ) : (
              <div className="text-[11px] text-slate-500">Run a scan first to generate a report.</div>
            )}
          </GlowCard>

          {/* Export */}
          <GlowCard className="p-4">
            <div className="text-xs font-semibold text-white mb-3">Export Report</div>
            <div className="space-y-2">
              {[
                { id: 'pdf', label: 'PDF Report', icon: FileText, color: 'text-amber-400', disabled: !result },
                { id: 'json', label: 'JSON Data', icon: Download, color: 'text-amber-400', disabled: !result },
                { id: 'csv', label: 'CSV Summary', icon: FileText, color: 'text-amber-400', disabled: !result },
              ].map(({ id, label, icon: Icon, color, disabled }) => (
                <button
                  key={id}
                  onClick={() => doExport(id as 'pdf' | 'json' | 'csv')}
                  disabled={disabled || exported.includes(id)}
                  className={`w-full flex items-center gap-2 p-2.5 rounded-lg glass border border-white/10 text-xs transition-all ${
                    exported.includes(id) ? 'text-emerald-400 border-emerald-500/30' : 'text-slate-400 hover:text-white hover:border-white/20'
                  } ${disabled ? 'opacity-40 cursor-not-allowed' : ''}`}
                >
                  <Icon size={12} className={exported.includes(id) ? 'text-emerald-400' : color} />
                  {exported.includes(id) ? 'Downloaded' : label}
                </button>
              ))}
            </div>
          </GlowCard>

          {/* Frame history */}
          {realTimeAnalysis && frameHistory.length > 0 && (
            <GlowCard className="p-4">
              <div className="flex items-center justify-between mb-3">
                <div className="text-xs font-semibold text-white">Live Analysis Timeline</div>
                <div className="flex items-center gap-1 text-[10px] text-emerald-400">
                  <Activity size={10} className="animate-pulse" />
                  {frameHistory.length} frames
                </div>
              </div>
              <div className="space-y-1.5 max-h-[200px] overflow-y-auto">
                {frameHistory.slice(0, 10).map((frame, i) => (
                  <div key={i} className="flex items-center justify-between text-[10px] p-1.5 rounded glass border border-white/5">
                    <span className="text-slate-500">#{frameHistory.length - i}</span>
                    <span className="text-slate-300">Score: {frame.score.toFixed(1)}%</span>
                    <span className={`${frame.fakeProbability > 70 ? 'text-rose-400' : frame.fakeProbability > 40 ? 'text-amber-400' : 'text-emerald-400'}`}>
                      {frame.fakeProbability.toFixed(1)}% fake
                    </span>
                  </div>
                ))}
              </div>
            </GlowCard>
          )}
        </div>
      </div>
    </div>
  );
}
