import { useState, useRef, useEffect } from 'react';
import { Leaf, Camera, AlertCircle, CheckCircle, FileText, X, Download, Trash2, BarChart3, Activity, Zap } from 'lucide-react';
import { RadarChart, PolarGrid, PolarAngleAxis, Radar, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Cell } from 'recharts';
import GlowCard from '@/components/ui/GlowCard';
import { getEcoScanDemo } from '@/lib/demoMode';

const demoItems = [
  { name: 'Plastic Bottle', icon: '🍶', carbon: 0.082, recyclable: true, material: 'PET Plastic', impact: 'medium' as const },
  { name: 'Cardboard Box', icon: '📦', carbon: 0.045, recyclable: true, material: 'Cardboard', impact: 'low' as const },
  { name: 'Styrofoam Cup', icon: '☕', carbon: 0.18, recyclable: false, material: 'Polystyrene', impact: 'high' as const },
  { name: 'Glass Bottle', icon: '🍾', carbon: 0.031, recyclable: true, material: 'Glass', impact: 'low' as const },
  { name: 'Aluminum Can', icon: '🥤', carbon: 0.067, recyclable: true, material: 'Aluminum', impact: 'low' as const },
];

const ecoMetrics = [
  { metric: 'Recyclability', score: 72 },
  { metric: 'Carbon', score: 58 },
  { metric: 'Biodegradable', score: 45 },
  { metric: 'Reusability', score: 63 },
  { metric: 'Toxicity', score: 81 },
  { metric: 'Energy', score: 68 },
];

interface ScanResult {
  item: typeof demoItems[0];
  quantity: number;
  sustainabilityScore: number;
  recommendations: string[];
  annualImpact: string;
  totalCarbon: number;
  scanId: string;
  scannedAt: Date;
}

interface ScanHistory {
  id: string;
  itemName: string;
  quantity: number;
  score: number;
  impact: string;
  timestamp: Date;
}

interface GeneratedReport {
  title: string;
  content: string;
  generatedAt: string;
}

function calculateEcoResult(item: typeof demoItems[0], qty: number): ScanResult {
  const score = item.impact === 'low' ? 78 : item.impact === 'medium' ? 55 : 32;
  const totalCarbon = item.carbon * qty;
  return {
    item,
    quantity: qty,
    sustainabilityScore: score,
    recommendations: item.recyclable
      ? [`Recycle this ${item.name.toLowerCase()} at your nearest recycling center`, `Choose refillable alternatives to reduce carbon by up to 70%`, `Consider bulk purchasing to minimize packaging waste`]
      : [`Avoid single-use ${item.material.toLowerCase()} — switch to biodegradable alternatives`, `Proper disposal required — do NOT place in recycling bins`, `Campaign for extended producer responsibility in your area`],
    annualImpact: `${(totalCarbon * 365).toFixed(1)} kg CO₂e annually`,
    totalCarbon,
    scanId: Math.random().toString(36).substring(2, 10),
    scannedAt: new Date(),
  };
}

function buildEcoReport(result: ScanResult): GeneratedReport {
  const impactLabel = result.item.impact === 'low' ? 'Low Impact' : result.item.impact === 'medium' ? 'Medium Impact' : 'High Impact';

  const content = `## Environmental Impact Report

**Report ID:** ${result.scanId}
**Generated:** ${result.scannedAt.toLocaleString()}
**Item:** ${result.item.name}
**Material:** ${result.item.material}
**Quantity:** ${result.quantity}

---

## Summary

**Sustainability Score:** ${result.sustainabilityScore}/100
**Impact Level:** ${impactLabel}
**Carbon per Item:** ${result.item.carbon} kg CO₂e
**Total Carbon (scanned):** ${result.totalCarbon.toFixed(3)} kg CO₂e
**Annual Impact:** ${result.annualImpact}
**Recyclable:** ${result.item.recyclable ? 'Yes' : 'No'}

## AI Recommendations

${result.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

## Next Steps

1. Review the sustainability score and identify improvement areas.
2. Implement the recommended actions to reduce environmental impact.
3. Schedule a follow-up scan in 30 days to measure improvement.
4. Share this report with stakeholders to drive collective action.

---
*Report generated by SpydeyVerse Eco-Scanner AI*`;

  return {
    title: `Eco Report — ${result.item.name}`,
    content,
    generatedAt: result.scannedAt.toISOString(),
  };
}

function downloadBlob(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

export default function EcoScanner() {
  const [selected, setSelected] = useState<typeof demoItems[0] | null>(null);
  const [qty, setQty] = useState(1);
  const [scanning, setScanning] = useState(false);
  const [result, setResult] = useState<ScanResult | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [aiAnalyzing, setAiAnalyzing] = useState(false);
  const [aiDetected, setAiDetected] = useState(false);
  const [history, setHistory] = useState<ScanHistory[]>([]);
  const [generatedReport, setGeneratedReport] = useState<GeneratedReport | null>(null);
  const [generatingReport, setGeneratingReport] = useState(false);
  const [exported, setExported] = useState<string[]>([]);
  const [cameraActive, setCameraActive] = useState(false);
  const [realTimeAnalysis, setRealTimeAnalysis] = useState(false);
  const [liveItem, setLiveItem] = useState<typeof demoItems[0] | null>(null);
  const [analysisFrame, setAnalysisFrame] = useState<string | null>(null);
  const [ecoScore, setEcoScore] = useState<number | null>(null);
  const [ecoRecommendations, setEcoRecommendations] = useState<string[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const analysisIntervalRef = useRef<number | null>(null);

  const MAX_IMAGE_DIMENSION = 512;
  const IMAGE_QUALITY = 0.7;

  async function compressImage(dataUrl: string): Promise<string> {
    return new Promise<string>((resolve) => {
      const img = new Image();
      img.onload = () => {
        let { width, height } = img;
        if (width > MAX_IMAGE_DIMENSION || height > MAX_IMAGE_DIMENSION) {
          const ratio = Math.min(MAX_IMAGE_DIMENSION / width, MAX_IMAGE_DIMENSION / height);
          width = Math.round(width * ratio);
          height = Math.round(height * ratio);
        }
        const canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          resolve(dataUrl);
          return;
        }
        ctx.drawImage(img, 0, 0, width, height);
        resolve(canvas.toDataURL('image/jpeg', IMAGE_QUALITY));
      };
      img.onerror = () => resolve(dataUrl);
      img.src = dataUrl;
    });
  }

  useEffect(() => {
    const saved = localStorage.getItem('eco_scan_history');
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        setHistory(parsed.map((h: ScanHistory) => ({ ...h, timestamp: new Date(h.timestamp) })));
      } catch { /* ignore */ }
    }
  }, []);

  useEffect(() => {
    if (history.length > 0) {
      localStorage.setItem('eco_scan_history', JSON.stringify(history));
    }
  }, [history]);

  useEffect(() => {
    return () => {
      if (analysisIntervalRef.current) {
        clearInterval(analysisIntervalRef.current);
      }
      if (streamRef.current) {
        streamRef.current.getTracks().forEach(track => track.stop());
      }
    };
  }, []);

  function findClosestDemoItem(name: string, material: string): typeof demoItems[0] {
    const best = demoItems.reduce((prev, curr) => {
      const nameScore = curr.name.toLowerCase().includes(name.toLowerCase()) || name.toLowerCase().includes(curr.name.toLowerCase()) ? 2 : 0;
      const materialScore = curr.material.toLowerCase().includes(material.toLowerCase()) || material.toLowerCase().includes(curr.material.toLowerCase()) ? 2 : 0;
      const prevScore = (prev.name.toLowerCase().includes(name.toLowerCase()) || name.toLowerCase().includes(prev.name.toLowerCase()) ? 2 : 0)
        + (prev.material.toLowerCase().includes(material.toLowerCase()) || material.toLowerCase().includes(prev.material.toLowerCase()) ? 2 : 0);
      return nameScore + materialScore > prevScore ? curr : prev;
    }, demoItems[0]);
    if (best.name.toLowerCase().includes(name.toLowerCase())) return best;
    return demoItems[Math.floor(Math.random() * demoItems.length)];
  }

  async function analyzeImageWithAI(dataUrl: string) {
    setAiAnalyzing(true);
    try {
      const scanResult = getEcoScanDemo(dataUrl);
      const baseItem = findClosestDemoItem(scanResult.result.name, scanResult.result.material);
      setSelected({
        ...baseItem,
        name: scanResult.result.name,
        material: scanResult.result.material,
        carbon: scanResult.result.carbon,
        recyclable: scanResult.result.recyclable,
        impact: scanResult.result.impact,
      });
      setAiDetected(true);
      setEcoScore(scanResult.sustainabilityScore);
      setEcoRecommendations(scanResult.recommendations);
    } catch (err) {
      console.warn('AI image analysis error:', err);
      setSelected(demoItems[Math.floor(Math.random() * demoItems.length)]);
      setAiDetected(false);
    } finally {
      setAiAnalyzing(false);
    }
  }

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = async () => {
        const rawDataUrl = reader.result as string;
        const dataUrl = await compressImage(rawDataUrl);
        setImagePreview(dataUrl);
        await analyzeImageWithAI(dataUrl);
      };
      reader.readAsDataURL(file);
    }
  }

  function clearImage() {
    setImagePreview(null);
    setSelected(null);
    setAiDetected(false);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  }

  async function startCamera() {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } }
      });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        setCameraActive(true);
      }
    } catch (err) {
      console.error('Camera access denied:', err);
      alert('Camera access is required for real-time analysis. Please allow camera permissions.');
    }
  }

  function stopCamera() {
    if (analysisIntervalRef.current) {
      clearInterval(analysisIntervalRef.current);
      analysisIntervalRef.current = null;
    }
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(track => track.stop());
      streamRef.current = null;
    }
    setCameraActive(false);
    setRealTimeAnalysis(false);
    setLiveItem(null);
    setAnalysisFrame(null);
  }

  function captureFrame(): string | null {
    if (!videoRef.current || !canvasRef.current) return null;
    const video = videoRef.current;
    const canvas = canvasRef.current;
    canvas.width = video.videoWidth || 640;
    canvas.height = video.videoHeight || 480;
    const ctx = canvas.getContext('2d');
    if (!ctx) return null;
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL('image/jpeg', 0.8);
  }

  function runRealTimeAnalysis() {
    if (!cameraActive) return;
    if (analysisIntervalRef.current) {
      clearInterval(analysisIntervalRef.current);
    }
    setRealTimeAnalysis(true);
    setLiveItem(null);
    setAnalysisFrame(null);

    analysisIntervalRef.current = window.setInterval(() => {
      const frame = captureFrame();
      if (!frame) return;

      const detectedItem = demoItems[Math.floor(Math.random() * demoItems.length)];
      const scoreVariation = () => (Math.random() * 10 - 5);

      setLiveItem({
        ...detectedItem,
        carbon: parseFloat((detectedItem.carbon + scoreVariation() * 0.01).toFixed(3)),
      });
      setAnalysisFrame(frame);
    }, 1200);
  }

  function stopRealTimeAnalysis() {
    if (analysisIntervalRef.current) {
      clearInterval(analysisIntervalRef.current);
      analysisIntervalRef.current = null;
    }
    setRealTimeAnalysis(false);
  }

  function runScan() {
    if (!selected) return;
    setScanning(true);
    setResult(null);
    setGeneratedReport(null);
    setTimeout(() => {
      const scanResult = calculateEcoResult(selected, qty);
      if (ecoScore !== null) {
        scanResult.sustainabilityScore = ecoScore;
      }
      if (ecoRecommendations.length > 0) {
        scanResult.recommendations = ecoRecommendations;
      }
      setResult(scanResult);
      setScanning(false);

      const historyEntry: ScanHistory = {
        id: scanResult.scanId,
        itemName: selected.name,
        quantity: qty,
        score: scanResult.sustainabilityScore,
        impact: selected.impact,
        timestamp: new Date(),
      };
      setHistory(prev => [historyEntry, ...prev.slice(0, 19)]);
    }, 1800);
  }

  function generateReport() {
    if (!result) return;
    setGeneratingReport(true);
    setGeneratedReport(null);
    setTimeout(() => {
      const report = buildEcoReport(result);
      setGeneratedReport(report);
      setGeneratingReport(false);
    }, 1200);
  }

  function doExport(format: 'pdf' | 'json' | 'csv') {
    if (!result) return;
    const base = result.item.name.toLowerCase().replace(/[^a-z0-9]+/g, '_');
    const timestamp = new Date().toISOString().slice(0, 19).replace(/[T:]/g, '-');
    const impactLabel = result.item.impact === 'low' ? 'Low Impact' : result.item.impact === 'medium' ? 'Medium Impact' : 'High Impact';

    if (format === 'json') {
      const payload = {
        scanId: result.scanId,
        item: result.item.name,
        material: result.item.material,
        quantity: result.quantity,
        sustainabilityScore: result.sustainabilityScore,
        impact: result.item.impact,
        carbonPerItem: result.item.carbon,
        totalCarbon: result.totalCarbon,
        annualImpact: result.annualImpact,
        recyclable: result.item.recyclable,
        recommendations: result.recommendations,
        scannedAt: result.scannedAt.toISOString(),
      };
      downloadBlob(JSON.stringify(payload, null, 2), `${base}_report_${timestamp}.json`, 'application/json');
    } else if (format === 'csv') {
      const escape = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`;
      const headers = ['Scan ID', 'Item', 'Material', 'Quantity', 'Score', 'Impact', 'Carbon/item', 'Total Carbon', 'Annual Impact', 'Recyclable'];
      const row = [
        result.scanId, result.item.name, result.item.material, result.quantity,
        result.sustainabilityScore, result.item.impact, result.item.carbon,
        result.totalCarbon.toFixed(3), result.annualImpact, result.item.recyclable ? 'Yes' : 'No'
      ].map(escape).join(',');
      const csv = `${headers.join(',')}\n${row}`;
      downloadBlob(csv, `${base}_report_${timestamp}.csv`, 'text/csv');
    } else if (format === 'pdf') {
      const report = generatedReport || buildEcoReport(result);
      const impactColorStyle = result.item.impact === 'low' ? 'color:#10b981' : result.item.impact === 'medium' ? 'color:#f59e0b' : 'color:#e01515';
      const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>${report.title}</title>
  <style>
    body { font-family: 'Inter', sans-serif; background: #000; color: #e2e8f0; margin: 0; padding: 32px; }
    h1 { font-size: 22px; color: #10b981; margin-bottom: 4px; }
    h2 { font-size: 14px; color: #065f46; border-bottom: 1px solid #052e16; padding-bottom: 6px; margin-top: 28px; }
    .meta { color: #64748b; font-size: 12px; margin-bottom: 24px; }
    .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0; }
    .card { background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.06); border-radius: 10px; padding: 16px; }
    .card .val { font-size: 22px; font-weight: 700; color: #10b981; }
    .card .lbl { font-size: 11px; color: #64748b; }
    .impact { font-size: 18px; font-weight: 700; margin: 16px 0; ${impactColorStyle} }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th { text-align: left; padding: 8px 10px; color: #64748b; border-bottom: 1px solid #052e16; }
    td { padding: 7px 10px; color: #cbd5e1; border-bottom: 1px solid rgba(255,255,255,0.03); }
    footer { margin-top: 48px; font-size: 10px; color: #334155; text-align: center; }
  </style>
</head>
<body>
  <h1>${report.title}</h1>
  <div class="meta">Generated: ${new Date().toLocaleString()} · Scan ID: ${result.scanId}</div>
  <div class="grid">
    <div class="card"><div class="val">${result.sustainabilityScore}/100</div><div class="lbl">Sustainability Score</div></div>
    <div class="card"><div class="val">${result.item.carbon} kg</div><div class="lbl">Carbon per Item</div></div>
    <div class="card"><div class="val">${result.totalCarbon.toFixed(3)} kg</div><div class="lbl">Total Carbon</div></div>
    <div class="card"><div class="val">${result.annualImpact}</div><div class="lbl">Annual Impact</div></div>
  </div>
  <h2>Impact Assessment</h2>
  <div class="impact">${impactLabel} Environmental Impact — ${result.item.material}</div>
  <h2>Recommendations</h2>
  <table>
    <tbody>
      ${result.recommendations.map((r, i) => `<tr><td>${i + 1}</td><td>${r}</td></tr>`).join('')}
    </tbody>
  </table>
  <footer>Generated by SpydeyVerse — Eco-Scanner AI</footer>
</body>
</html>`;
      downloadBlob(html, `${base}_report_${timestamp}.html`, 'text/html');
    }
    setExported(prev => [...prev, format]);
    setTimeout(() => setExported(prev => prev.filter(x => x !== format)), 3000);
  }

  const impactColor = (impact: string) =>
    impact === 'low' ? 'text-emerald-400' : impact === 'medium' ? 'text-amber-400' : 'text-rose-400';

  const chartData = demoItems.map(item => ({
    name: item.name.slice(0, 12),
    carbon: item.carbon,
    recyclable: item.recyclable ? 1 : 0,
  }));

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-green-500 to-emerald-500 flex items-center justify-center">
            <Leaf size={20} className="text-white" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-white">Eco-Scanner AI</h2>
            <p className="text-xs text-slate-500">Environmental impact analysis with ML-powered sustainability scoring</p>
          </div>
        </div>
        {result && (
          <div className="flex items-center gap-2">
            <span className="text-[10px] px-2 py-1 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              Score: {result.sustainabilityScore}/100
            </span>
          </div>
        )}
        {cameraActive && (
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1.5 text-xs text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-3 py-1.5 rounded-xl">
              <Activity size={11} className={realTimeAnalysis ? 'animate-pulse' : ''} />
              {realTimeAnalysis ? 'Live Analysis' : 'Camera Active'}
            </div>
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Scanner panel */}
        <div className="lg:col-span-2 space-y-4">
          <GlowCard className="p-6">
            <div className="text-xs font-semibold text-white mb-4">Item Detection & Analysis</div>

            {/* Real-time camera mode */}
            {!cameraActive ? (
              <div className="mb-4">
                <div className="text-[11px] text-slate-500 mb-2">Real-Time Analysis</div>
                <button
                  onClick={startCamera}
                  className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-green-500 to-emerald-500 text-white text-xs font-semibold hover:opacity-90 transition-all"
                >
                  <Camera size={13} /> Start Camera
                </button>
                <div className="text-[10px] text-slate-600 mt-1.5">Enable camera for real-time waste detection</div>
              </div>
            ) : (
              <div className="mb-4 space-y-3">
                <div className="relative rounded-xl overflow-hidden border border-white/10 bg-black">
                  <video
                    ref={videoRef}
                    autoPlay
                    playsInline
                    muted
                    className="w-full max-h-[360px] object-contain"
                  />
                  {realTimeAnalysis && analysisFrame && (
                    <div className="absolute inset-0 pointer-events-none">
                      <div className="absolute top-3 left-3 flex items-center gap-1.5 px-2 py-1 rounded-lg bg-black/60 text-[10px] text-emerald-400 border border-emerald-500/30">
                        <Activity size={10} className="animate-pulse" />
                        LIVE
                      </div>
                      {liveItem && (
                        <div className="absolute bottom-3 left-3 right-3 px-3 py-2 rounded-lg text-xs font-medium border bg-emerald-500/20 border-emerald-500/30 text-emerald-400">
                          Detected: {liveItem.name} · {liveItem.material} · {liveItem.carbon} kg CO₂e
                        </div>
                      )}
                    </div>
                  )}
                </div>
                <div className="flex gap-2">
                  {!realTimeAnalysis ? (
                    <button
                      onClick={runRealTimeAnalysis}
                      className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-green-500 to-emerald-500 text-white text-xs font-semibold hover:opacity-90 transition-all"
                    >
                      <Zap size={13} /> Start Real-Time Analysis
                    </button>
                  ) : (
                    <button
                      onClick={stopRealTimeAnalysis}
                      className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-rose-500 to-orange-500 text-white text-xs font-semibold hover:opacity-90 transition-all"
                    >
                      <Activity size={13} /> Stop Analysis
                    </button>
                  )}
                  <button
                    onClick={stopCamera}
                    className="flex items-center gap-2 px-4 py-2 rounded-xl glass border border-white/10 text-slate-400 text-xs hover:text-white transition-all"
                  >
                    Stop Camera
                  </button>
                  {realTimeAnalysis && liveItem && (
                    <button
                      onClick={() => {
                        setSelected(liveItem);
                        stopCamera();
                      }}
                      className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 text-white text-xs font-semibold hover:opacity-90 transition-all"
                    >
                      <CheckCircle size={13} /> Use Detected Item
                    </button>
                  )}
                </div>
              </div>
            )}

            {/* Hidden canvas for frame capture */}
            <canvas ref={canvasRef} className="hidden" />

            {/* Divider */}
            {cameraActive && (
              <div className="flex items-center gap-3 my-4">
                <div className="flex-1 h-px bg-white/5" />
                <div className="text-[10px] text-slate-600">OR</div>
                <div className="flex-1 h-px bg-white/5" />
              </div>
            )}

            {/* Camera / Upload area */}
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              capture="environment"
              className="hidden"
              onChange={handleFileChange}
            />
            <div
              onClick={() => fileInputRef.current?.click()}
              className="relative border-2 border-dashed border-white/10 rounded-xl p-6 text-center hover:border-emerald-500/30 transition-colors cursor-pointer mb-4 group overflow-hidden"
            >
              <div className="absolute inset-0 scan-line opacity-0 group-hover:opacity-100 transition-opacity" />
               {imagePreview ? (
                 <div className="relative">
                   <img src={imagePreview} alt="Preview" className="max-h-48 mx-auto rounded-lg mb-3 object-contain" />
                   <button
                     onClick={(e) => { e.stopPropagation(); clearImage(); }}
                     className="absolute top-2 right-2 w-6 h-6 rounded-full bg-black/60 text-white flex items-center justify-center hover:bg-black/80 transition-colors"
                   >
                     <X size={12} />
                   </button>
                   <div className="text-xs font-medium text-emerald-400">Image uploaded — ready to scan</div>
                    {aiAnalyzing && (
                      <div className="absolute inset-0 bg-black/60 rounded-lg flex flex-col items-center justify-center gap-2">
                        <div className="w-4 h-4 spinner" />
                        <span className="text-[10px] text-emerald-400">AI analyzing image…</span>
                      </div>
                    )}
                    {aiDetected && selected && (
                      <div className="absolute bottom-0 left-0 right-0 bg-emerald-500/10 border-t border-emerald-500/20 text-[9px] text-emerald-400 px-2 py-1">
                        ✓ AI-detected: {selected.name}
                      </div>
                    )}
                  </div>
                ) : (
                 <>
                   <Camera size={28} className="text-slate-600 mx-auto mb-2 group-hover:text-emerald-400 transition-colors" />
                   <div className="text-xs font-medium text-slate-400 group-hover:text-white transition-colors">
                     Camera Scan / Upload Image
                   </div>
                    <div className="text-[10px] text-slate-600 mt-1">AI detects waste type, material, quantity</div>
                    <div className="text-[9px] mt-1 flex items-center gap-1.5">
                      <div className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                      <span className="text-emerald-400">
                        AI Vision Analysis Available
                      </span>
                   </div>
                </>
              )}
            </div>

            {/* Demo item selection */}
            <div className="mb-4">
              <div className="text-[11px] text-slate-500 mb-2">Select demo item to analyze:</div>
              <div className="grid grid-cols-5 gap-2">
                {demoItems.map(item => (
                  <button
                    key={item.name}
                    onClick={() => setSelected(item)}
                    className={`flex flex-col items-center gap-1 p-3 rounded-xl transition-all ${
                      selected?.name === item.name
                        ? 'bg-emerald-500/20 border border-emerald-500/40'
                        : 'glass border border-white/10 hover:border-white/20'
                    }`}
                  >
                    <span className="text-xl">{item.icon}</span>
                    <span className="text-[9px] text-slate-400 text-center leading-tight">{item.name}</span>
                  </button>
                ))}
              </div>
            </div>

            {selected && (
              <div className="flex items-center gap-3 mb-4">
                <div className="text-xs text-slate-400">Quantity:</div>
                <div className="flex items-center gap-2">
                  <button onClick={() => setQty(Math.max(1, qty - 1))} className="w-7 h-7 rounded-lg glass border border-white/10 text-white flex items-center justify-center hover:bg-white/10 transition-colors">-</button>
                  <span className="text-sm font-medium text-white w-8 text-center">{qty}</span>
                  <button onClick={() => setQty(qty + 1)} className="w-7 h-7 rounded-lg glass border border-white/10 text-white flex items-center justify-center hover:bg-white/10 transition-colors">+</button>
                </div>
                 <div className="ml-auto text-[11px] text-slate-500">{selected.name} · {selected.material}</div>
                 {aiDetected && (
                   <span className="ml-2 text-[9px] px-1.5 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">AI-detected</span>
                 )}
              </div>
            )}

            <button
              onClick={runScan}
              disabled={!selected || scanning}
              className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-green-500 to-emerald-500 text-white text-xs font-semibold hover:opacity-90 disabled:opacity-50 transition-all btn-glow"
            >
              {scanning ? <><span className="w-3 h-3 spinner" />Scanning...</> : <><Leaf size={13} />Analyze Environmental Impact</>}
            </button>
          </GlowCard>

          {/* Results */}
          {result && (
            <GlowCard className="p-5">
              <div className="text-xs font-semibold text-white mb-4">Environmental Impact Report</div>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-5">
                {[
                  { label: 'Sustainability Score', value: `${result.sustainabilityScore}/100`, color: result.sustainabilityScore >= 70 ? 'text-emerald-400' : result.sustainabilityScore >= 50 ? 'text-amber-400' : 'text-rose-400' },
                  { label: 'Carbon per Item', value: `${result.item.carbon}kg CO₂e`, color: 'text-red-400' },
                  { label: 'Annual Impact', value: result.annualImpact, color: 'text-amber-400' },
                  { label: 'Recyclable', value: result.item.recyclable ? 'Yes' : 'No', color: result.item.recyclable ? 'text-emerald-400' : 'text-rose-400' },
                ].map(({ label, value, color }) => (
                  <div key={label} className="glass rounded-xl p-3 border border-white/5 text-center">
                    <div className={`text-sm font-bold ${color}`}>{value}</div>
                    <div className="text-[10px] text-slate-600 mt-0.5">{label}</div>
                  </div>
                ))}
              </div>

              {/* Impact level */}
              <div className={`flex items-center gap-2 p-3 rounded-xl border mb-4 ${
                result.item.impact === 'low' ? 'bg-emerald-500/5 border-emerald-500/20' :
                result.item.impact === 'medium' ? 'bg-amber-500/5 border-amber-500/20' :
                'bg-rose-500/5 border-rose-500/20'
              }`}>
                {result.item.impact === 'low' ? <CheckCircle size={14} className="text-emerald-400" /> : <AlertCircle size={14} className={impactColor(result.item.impact)} />}
                <div>
                  <div className={`text-xs font-semibold ${impactColor(result.item.impact)}`}>
                    {result.item.impact.charAt(0).toUpperCase() + result.item.impact.slice(1)} Environmental Impact
                  </div>
                  <div className="text-[10px] text-slate-500">{result.item.material} · {result.item.recyclable ? 'Recyclable' : 'Not recyclable'}</div>
                </div>
              </div>

              {/* Recommendations */}
              <div className="text-[11px] text-slate-500 font-medium mb-2">AI Recommendations</div>
              <div className="space-y-2">
                {result.recommendations.map((rec, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs text-slate-400">
                    <div className="w-4 h-4 rounded-full bg-emerald-500/10 flex items-center justify-center flex-shrink-0 mt-0.5">
                      <span className="text-emerald-400 text-[9px] font-bold">{i + 1}</span>
                    </div>
                    {rec}
                  </div>
                ))}
              </div>
            </GlowCard>
          )}
        </div>

        {/* Right panel */}
        <div className="space-y-4">
          {/* Radar chart */}
          <GlowCard className="p-4">
            <div className="text-xs font-semibold text-white mb-1">Eco Metrics Radar</div>
            <div className="text-[11px] text-slate-500 mb-2">Multi-factor sustainability</div>
            <ResponsiveContainer width="100%" height={200}>
              <RadarChart data={ecoMetrics}>
                <PolarGrid stroke="rgba(16,185,129,0.1)" />
                <PolarAngleAxis dataKey="metric" tick={{ fill: '#475569', fontSize: 9 }} />
                <Radar name="Score" dataKey="score" stroke="#10b981" fill="#10b981" fillOpacity={0.15} strokeWidth={1.5} />
              </RadarChart>
            </ResponsiveContainer>
          </GlowCard>

          {/* Carbon comparison chart */}
          <GlowCard className="p-4">
            <div className="text-xs font-semibold text-white mb-1">Carbon Comparison</div>
            <div className="text-[11px] text-slate-500 mb-2">CO₂e per item</div>
            <ResponsiveContainer width="100%" height={160}>
              <BarChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(16,185,129,0.08)" />
                <XAxis dataKey="name" tick={{ fill: '#475569', fontSize: 8 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fill: '#475569', fontSize: 9 }} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={{ background: '#0f172a', border: '1px solid rgba(16,185,129,0.2)', borderRadius: 8, fontSize: 11 }} />
                <Bar dataKey="carbon" name="kg CO₂e" radius={[3,3,0,0]}>
                  {chartData.map((entry, index) => (
                    <Cell key={index} fill={entry.recyclable ? '#10b981' : '#e01515'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </GlowCard>

          {/* Materials guide */}
          <GlowCard className="p-4">
            <div className="text-xs font-semibold text-white mb-3">Material Classification</div>
            <div className="space-y-2">
              {demoItems.map(item => (
                <div key={item.name} className="flex items-center gap-2">
                  <span className="text-base">{item.icon}</span>
                  <div className="flex-1">
                    <div className="flex justify-between">
                      <span className="text-[11px] text-slate-400">{item.name}</span>
                      <span className={`text-[10px] font-medium ${impactColor(item.impact)}`}>{item.impact}</span>
                    </div>
                    <div className="text-[10px] text-slate-600">{item.carbon}kg CO₂e</div>
                  </div>
                </div>
              ))}
            </div>
          </GlowCard>

          {/* Report generation */}
          <GlowCard className="p-4">
            <div className="text-xs font-semibold text-white mb-3">Generate Report</div>
            {result ? (
              <div className="space-y-2">
                <button
                  onClick={generateReport}
                  disabled={generatingReport}
                  className="w-full flex items-center gap-2 p-2.5 rounded-lg bg-gradient-to-r from-green-500 to-emerald-500 text-white text-xs font-semibold hover:opacity-90 disabled:opacity-50 transition-all"
                >
                  {generatingReport ? <><span className="w-3 h-3 spinner" />Generating...</> : <><FileText size={12} />Generate Report</>}
                </button>
                {generatedReport && (
                  <div className="text-[10px] text-emerald-400 flex items-center gap-1">
                    <CheckCircle size={10} /> Report ready for export
                  </div>
                )}
              </div>
            ) : (
              <div className="text-[11px] text-slate-500">Run a scan first to generate a report.</div>
            )}
          </GlowCard>

          {/* Export */}
          <GlowCard className="p-4">
            <div className="text-xs font-semibold text-white mb-3">Export Reports</div>
            <div className="space-y-1">
              {[
                { id: 'pdf', label: 'PDF Report', icon: FileText, color: 'text-emerald-400' },
                { id: 'json', label: 'JSON Data', icon: Download, color: 'text-emerald-400' },
                { id: 'csv', label: 'CSV Summary', icon: FileText, color: 'text-emerald-400' },
              ].map(({ id, label, icon: Icon, color }) => (
                <button
                  key={id}
                  onClick={() => doExport(id as 'pdf' | 'json' | 'csv')}
                  disabled={!result || exported.includes(id)}
                  className={`w-full flex items-center gap-2 p-2.5 rounded-lg glass border border-white/10 text-xs transition-all ${
                    exported.includes(id) ? 'text-emerald-400 border-emerald-500/30' : 'text-slate-400 hover:text-white hover:border-white/20'
                  } ${!result ? 'opacity-40 cursor-not-allowed' : ''}`}
                >
                  <Icon size={12} className={exported.includes(id) ? 'text-emerald-400' : color} />
                  {exported.includes(id) ? 'Downloaded' : label}
                </button>
              ))}
            </div>
          </GlowCard>

          {/* Scan history */}
          <GlowCard className="p-4">
            <div className="flex items-center justify-between mb-3">
              <div className="text-xs font-semibold text-white">Recent Scans</div>
              {history.length > 0 && (
                <button onClick={() => { setHistory([]); localStorage.removeItem('eco_scan_history'); }} className="text-[10px] text-slate-500 hover:text-rose-400 transition-colors flex items-center gap-1">
                  <Trash2 size={10} /> Clear
                </button>
              )}
            </div>
            <div className="space-y-2 max-h-[200px] overflow-y-auto">
              {history.length === 0 ? (
                <div className="text-[11px] text-slate-600 text-center py-3">No scans yet. Analyze an item to get started.</div>
              ) : (
                history.map(h => (
                  <div key={h.id} className="flex items-center gap-2 p-2 rounded-lg hover:bg-white/5 transition-colors">
                    <BarChart3 size={12} className="text-emerald-400 flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <div className="text-[11px] text-slate-400 truncate">{h.itemName} × {h.quantity}</div>
                      <div className="text-[10px] text-slate-600">{h.timestamp.toLocaleTimeString()} · Score: {h.score}</div>
                    </div>
                    <span className={`text-[10px] font-medium ${impactColor(h.impact)}`}>{h.impact}</span>
                  </div>
                ))
              )}
            </div>
          </GlowCard>
        </div>
      </div>
    </div>
  );
}
